title: Insurance Knowledge Repo
description: Public insurance knowledge base
remote_theme: just-the-docs/just-the-docs
url: https://gg38040.github.io/Insurance-Knowledge-Repo
baseurl: ""

# Make sure PDFs and static files are included
include:
  - "*.pdf"
